config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'client_landing' => 'welcome#client_landing'
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show, :update, :create, :destroy]
  delete 'delete_client' => 'users#destroy', as: :delete_client
  get 'change_password_cleanser' => 'users#change_password_cleanser', as: :change_password_cleanser
  
  resources :weddings, only: [:show, :update, :create]
  get 'add_wedding/:id' => 'weddings#create', as: :add_wedding
  
  get 'temporary_password_cleanser/:id' => 'invitations#destroy', as: :temporary_password_cleanser
  get 'confirmation' => 'invitations#confirmation'
  get 'send_invitation/:id' => 'invitations#create', as: :send_invitation
  
  resources :invoices
  resources :items
  post 'create_charge/:id' => 'charges#create', as: :create_charge
  get 'new_charge/:id' => 'charges#new', as: :new_charge
  get 'new_payment/:id' => 'charges#payment', as: :new_payment

  resources :collections, only: [:index, :create, :edit, :update, :destroy]
  resources :images, only: [:create, :destroy]

  get 'gallery_images/:genre' => 'images#gallery_images'
  get 'add_image/:genre' => "images#add_image"

  resources :reviews, only: [:create, :update, :destroy]
  get 'get_reviews/:genre' => 'reviews#reviews'

  resources :webgalleries, only: [:create, :destroy]
  
  resources :portraits, except: [:new]
  get 'new_portrait/:id' => 'portraits#new', as: :new_portrait
  
  
  
  
  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :collection

	def url
		return "http://bteamphoto.com/images/#{genre}/#{name}"
	end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  before_create :generate_token
  
  private
  
  def generate_token
    self.token = "#{ SecureRandom.urlsafe_base64 }"
  end
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :invoiceable, polymorphic: true
  monetize :balance_cents
  monetize :payment_cents
  has_many :items

  before_create :set_default_tax_rate_if_nil

  def set_default_tax_rate_if_nil
  	self.tax_rate ||= ".08"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice
  monetize :price_cents
end

app/models/portrait.rb
class Portrait < ActiveRecord::Base
  belongs_to :user
  has_many :invoices, as: :invoiceable
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  has_one :wedding, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :webgalleries, dependent: :destroy
  has_many :portraits, dependent: :destroy
  
  # User roles
  def admin?
    role == 'admin'
  end
  
  def client?
    role == 'client'
  end
  
end

app/models/webgallery.rb
class Webgallery < ActiveRecord::Base
  belongs_to :user
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
  belongs_to :user 
  has_many :invoices, as: :invoiceable
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
  	@collections = Collection.all
  	@collection = Collection.new
  end

  def create
  	@collection = Collection.new(collection_params).save
  	redirect_to collections_path
  end

  def edit
  	@collection = Collection.find(params[:id])
    @images = @collection.images.all
    @image = Image.new
  end

  def update
  	@collection = Collection.find(params[:id])
  	@collection.update_attributes(collection_params)
  	redirect_to collections_path
  end

  def destroy
  	@collection = Collection.find(params[:id])
  	@collection.destroy
  	redirect_to collections_path
  end

  private

  def collection_params
  	params.require(:collection).permit(:name, :description, :genre)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def helper_my_business_name
    return 'B-Team Photography'
  end
  
  def helper_title_slogan
    return 'B-Team Photography - Professional Wedding and Portrait Photographers'
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tax_rate_helper.rb
module TaxRateHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/collections/create.html.erb
<h1>Collections#create</h1>
<p>Find me in app/views/collections/create.html.erb</p>

app/views/collections/destroy.html.erb
<h1>Collections#destroy</h1>
<p>Find me in app/views/collections/destroy.html.erb</p>

app/views/collections/edit.html.erb
<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">

  	<p class="large-text">Edit Collection</p>

    <!-- Update Collection Info -->
  	<%= form_for @collection do |f| %>

      <span>Name:</span>
      <%= f.text_field :name %>
        
      <span>Description:</span>
      <%= f.text_field :description %>

      <span>Genre:</span>
      <%= f.text_field :genre %>

	    <%= f.submit 'Update', class: 'button small radius secondary' %>

    <% end %>

    <p class="large-text">Photographs</p>

    <!-- Add Photos -->
    <%= form_for @image do |f| %>

      <span>Name:</span>
      <%= f.text_field :name %>
        
      <span>Description:</span>
      <%= f.text_field :description %>

      <!-- Inherit genre and id from collection -->
      <%= f.hidden_field :genre, value: @collection.genre %>
      <%= f.hidden_field :collection_id, value: @collection.id %>

      <%= f.submit 'Add Photo', class: 'button small radius secondary' %>

    <% end %>

    <!-- List Photos -->

    <% @images.each do |image| %>
      <p id="image-<%= image.id %>">
        <img class="thumbnail" src="<%= image.url %>">
        <br/>
        <span> <%= image.name %> </span>
        <%= link_to 'Delete', image, method: :delete, class: 'label round secondary', remote: true %>
      </p>
    <% end %>

    <br/>
	  <%= link_to 'Back', collections_path %>
		<br/><br/>  

	</div>
</div>

app/views/collections/index.html.erb
<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">

  	<p class="large-text">Add Collection</p>

  	<%= form_for @collection do |f| %>

      <span>Name:</span>
      <%= f.text_field :name %>
        
      <span>Description:</span>
      <%= f.text_field :description %>

      <span>Genre:</span>
      <%= f.text_field :genre %>

	    <%= f.submit 'Add Collection', class: 'button small radius secondary' %>

    <% end %>

    <p class="large-text">Photo Collections</p>

    <% @collections.each do |collection| %>
    	<p>
	    	<%= link_to collection.name, edit_collection_path(collection) %> 
	    	<%= link_to 'Delete', collection, method: :delete, class: 'label round secondary' %>
        <br/>
        <% collection.images.each do |image| %>
          <img class="thumbnail-tiny" src="<%= image.url %>" %>
        <% end %>
    	</p>
    <% end %>  

	</div>
</div>