config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'client_landing' => 'welcome#client_landing'
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show, :update, :create, :destroy]
  delete 'delete_client' => 'users#destroy', as: :delete_client
  get 'change_password_cleanser' => 'users#change_password_cleanser', as: :change_password_cleanser
  
  resources :weddings, only: [:show, :update, :create]
  get 'add_wedding/:id' => 'weddings#create', as: :add_wedding
  
  get 'temporary_password_cleanser/:id' => 'invitations#destroy', as: :temporary_password_cleanser
  get 'confirmation' => 'invitations#confirmation'
  get 'send_invitation/:id' => 'invitations#create', as: :send_invitation
  
  resources :invoices
  resources :items
  post 'create_charge/:id' => 'charges#create', as: :create_charge
  get 'new_charge/:id' => 'charges#new', as: :new_charge
  get 'new_payment/:id' => 'charges#payment', as: :new_payment

  resources :collections, only: [:index, :create, :edit, :update, :destroy]
  resources :images, only: [:create, :destroy]

  get 'gallery_images/:genre' => 'images#gallery_images'
  get 'add_image/:genre' => "images#add_image"

  resources :reviews, only: [:create, :update, :destroy]
  get 'get_reviews/:genre' => 'reviews#reviews'

  resources :webgalleries, only: [:create, :destroy]
  
  resources :portraits, except: [:new]
  get 'new_portrait/:id' => 'portraits#new', as: :new_portrait
  
  
  
  
  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :collection

	def url
		return "http://bteamphoto.com/images/#{genre}/#{name}"
	end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  before_create :generate_token
  
  private
  
  def generate_token
    self.token = "#{ SecureRandom.urlsafe_base64 }"
  end
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :invoiceable, polymorphic: true
  monetize :balance_cents
  monetize :payment_cents
  has_many :items

  before_create :set_default_tax_rate_if_nil

  def set_default_tax_rate_if_nil
  	self.tax_rate ||= ".08"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice
  monetize :price_cents
end

app/models/portrait.rb
class Portrait < ActiveRecord::Base
  belongs_to :user
  has_many :invoices, as: :invoiceable
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  has_one :wedding, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :webgalleries, dependent: :destroy
  has_many :portraits, dependent: :destroy
  
  # User roles
  def admin?
    role == 'admin'
  end
  
  def client?
    role == 'client'
  end
  
end

app/models/webgallery.rb
class Webgallery < ActiveRecord::Base
  belongs_to :user
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
  belongs_to :user 
  has_many :invoices, as: :invoiceable
end

app/controllers/invoices_controller.rb
require 'bigdecimal'
class InvoicesController < ApplicationController
  
  def create   
    @invoice = Invoice.new(params.require(:invoice).permit(:description, :balance, :invoiceable_id, :invoiceable_type, :tax_rate))
    # default tax rate is set before create if none given (see model)
    # default payment_cents is 0 to start, as a monetized column cannot be nil
    @invoice.payment_cents = 0
    @invoice.save
    redirect_to @invoice
  end
  
  def update
    @invoice = Invoice.find(params[:id])
    @invoice.update_attributes(params.require(:invoice).permit(:description, :balance, :tax_rate, :payment))

    # direct based on payment amount: 0 => invoice, >0 => cc charge 
    if @invoice.payment_cents == 0
      redirect_to @invoice 
    else
      redirect_to new_charge_path(@invoice)
    end
  end
  
  def show
    @invoice = Invoice.find(params[:id])
    # return user based on the parent class name of the invoice (constantized method)
    @user = @invoice.invoiceable_type.constantize.find(@invoice.invoiceable_id).user
    @parent_type = @invoice.invoiceable_type.constantize.find(@invoice.invoiceable_id)
    @item = Item.new
    @items = @invoice.items.all
    # take the math logic in the view and move it here into the controller

    # sum up item prices for invoice subtotal
    @invoice_subtotal = 0
    @items.each { |item| @invoice_subtotal+=item.price }

    # Old method as explanation (06-11-15)
    # @items.each do |item|
    #   @invoice_subtotal = @invoice_subtotal + item.price
    # end

    # calculate tax on subtotal (convert decimal calculation to integer for cents)
    @invoice_tax = Money.new((@invoice.tax_rate * @invoice_subtotal.to_d) * 100)

    # sum up grand total
    @invoice_grand_total = @invoice_subtotal + @invoice_tax

    # reset payment to 0
    @invoice.update_attributes(payment_cents: 0)
  end
  
  def destroy
    @invoice = Invoice.find(params[:id]).destroy
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def helper_my_business_name
    return 'B-Team Photography'
  end
  
  def helper_title_slogan
    return 'B-Team Photography - Professional Wedding and Portrait Photographers'
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tax_rate_helper.rb
module TaxRateHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/invoices/_invoiceinfo.html.erb
<%= form_for invoice do |f| %>

  <div class="row">
    <div class="small-10 small-centered large-10 large-uncentered columns">
      <span>Description:</span>    
      <%= f.text_field :description %> 
      <span>Total Balance Due:</span>    
      <%= f.text_field :balance %>
      <span>Tax Rate (leave blank if default):</span>
      <%= f.text_field :tax_rate %>
      
      <!-- invoiceable params -->
      <%= f.hidden_field :invoiceable_id %>
      <%= f.hidden_field :invoiceable_type %>
    </div>
  </div>

  <!-- Submit -->

  <div class="row">
    <div class="small-10 small-centered large-10 large-uncentered columns">
      <br/><%= f.submit 'Add Invoice', class: 'button small radius secondary' %> 
    </div>
  </div>

<% end %>

app/views/invoices/show.html.erb
<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">
    
    
    <% if current_user.admin? %>
      <p class="large-text">Update Invoice Details</p>
      <%= form_for @invoice do |f| %>
        <span>Description:</span><br/>
        <%= f.text_field :description %>
        <span>Balance:</span><br/>
        <%= f.text_field :balance %>
        <span>Tax Rate:</span>
        <%= f.text_field :tax_rate %>
        <%= f.submit "Update", class: 'button small radius secondary' %>
        <%= link_to "Delete Invoice", @invoice, method: :delete, class: 'button small radius secondary', data: { confirm: "Are you sure you want to delete this invoice?" } %>
      <% end %>
    <% else %>
      <p class="large-text">
        <%= @invoice.description %>
      </p>
    <% end %>

    
    <p>
      <span><%= @user.name_primary %></span><br/>
      <span><%= @user.street_address %></span><br/>
      <span><%= @user.city %>, <%= @user.state %> <%= @user.zip_code %></span><br/>
    </p>
    
    
    <!-- rename table class to something more re-usable -->
    <table class="table-width-100">
      <thead>
        <tr>
          <th class="table-header-width-75">
            <span>Description</span>
          </th>
          <th class="table-header-width-25">
            <span>Price</span>
          </th>
        </tr>
      </thead>
      <tbody>
        
        <!-- each block starts here for items -->
        <% @items.each do |item| %>
        <tr>
          <td>
            <span><%= item.description %> 
              <% if current_user.admin? %>
                <%= link_to "Remove", item, method: :delete, class: 'right label round secondary' %></span>
              <% end %>
          </td>
          <td>
            <span><%= humanized_money_with_symbol(item.price) %></span>
          </td>
        </tr>
        <% end %>
        <!-- each block ends here for items -->

        <% if current_user.admin? %>
        <!-- Add new items -->
          <tr>
            <td>
              <%= form_for @item do |f| %>
                <%= f.hidden_field :invoice_id, value: @invoice.id %>
                <%= f.label :description %>
                <%= f.text_field :description %>
                <%= f.label :price %>
                <%= f.text_field :price %>
                <%= f.submit "Add Item", class: 'button tiny radius secondary' %>
              <% end %>
            </td>
            <td>
              <span></span>
            </td>
          </tr>
        <% end %>
        
        <!-- Totals -->
        <tr>
          <td>
            <span class="right">Subtotal:</span><br/>
            <span class="right">Tax:</span><br/>
            <span class="right">Grand Total:</span><br/>
          </td>
          <td>
            <span><%= humanized_money_with_symbol(@invoice_subtotal) %></span><br/>
            <span><%= humanized_money_with_symbol(@invoice_tax) %></span><br/>
            <span><%= humanized_money_with_symbol(@invoice_grand_total) %></span><br/>
          </td>
        </tr>
        
      </tbody>
      <tfoot>
        <tr>
          <td>
            <span>Balance due:</span>
            <% if @invoice.balance > 0 %>
              <!-- link_to "Make Payment", new_payment_path(@invoice), class: 'label round secondary right' -->
            <% else %>
              <span class="label round success right">Paid</span>
            <% end %>
          </td>
          <td>
            <span><%= humanized_money_with_symbol(@invoice.balance) %></span>
          </td>
        </tr>
      </tfoot>
    </table>

    <!-- Payment selection -->
    <% if @invoice.balance > 0 %>
      <%= form_for @invoice do |f| %>
        <fieldset>
          <legend>Online Payments</legend>
          <span>Enter Amount:</span>
          <div class="row">
            <div class="large-12">
              <div class="row-collapse">
                <div class="large-4 small-6 columns">
                  <%= f.text_field :payment %>
                </div>
                <div class="large-8 small-6 columns">
                  <%= f.submit 'Make Payment', class: 'button tiny radius secondary inline' %>
                </div>
              </div>
            </div>
          </div>
        </fieldset>
      <% end %>
    <% end %>
    
    <br/>
    <% if current_user.admin? %>
      <%= link_to "Back", @parent_type %> | <%= link_to "Back to Client Index", users_path %>
    <% else %>
      <%= link_to "Back", :back %> | <%= link_to "Back to My Details", client_landing_path %>
    <% end %>
    <br/><br/><br/>
    
  </div>
</div>