config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'client_landing' => 'welcome#client_landing'
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show, :update, :create, :destroy]
  delete 'delete_client' => 'users#destroy', as: :delete_client
  get 'change_password_cleanser' => 'users#change_password_cleanser', as: :change_password_cleanser
  
  resources :weddings, only: [:show, :update, :create]
  get 'add_wedding/:id' => 'weddings#create', as: :add_wedding
  
  get 'temporary_password_cleanser/:id' => 'invitations#destroy', as: :temporary_password_cleanser
  get 'confirmation' => 'invitations#confirmation'
  get 'send_invitation/:id' => 'invitations#create', as: :send_invitation
  
  resources :invoices
  resources :items
  post 'create_charge/:id' => 'charges#create', as: :create_charge
  get 'new_charge/:id' => 'charges#new', as: :new_charge
  get 'new_payment/:id' => 'charges#payment', as: :new_payment

  resources :collections, only: [:index, :create, :edit, :update, :destroy]
  resources :images, only: [:create, :destroy]

  get 'gallery_images/:genre' => 'images#gallery_images'
  get 'add_image/:genre' => "images#add_image"

  resources :reviews, only: [:create, :update, :destroy]
  get 'get_reviews/:genre' => 'reviews#reviews'

  resources :webgalleries, only: [:create, :destroy]
  
  resources :portraits, except: [:new]
  get 'new_portrait/:id' => 'portraits#new', as: :new_portrait
  
  
  
  
  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :collection

	def url
		return "http://bteamphoto.com/images/#{genre}/#{name}"
	end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  before_create :generate_token
  
  private
  
  def generate_token
    self.token = "#{ SecureRandom.urlsafe_base64 }"
  end
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :invoiceable, polymorphic: true
  monetize :balance_cents
  monetize :payment_cents
  has_many :items

  before_create :set_default_tax_rate_if_nil

  def set_default_tax_rate_if_nil
  	self.tax_rate ||= ".08"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice
  monetize :price_cents
end

app/models/portrait.rb
class Portrait < ActiveRecord::Base
  belongs_to :user
  has_many :invoices, as: :invoiceable
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  has_one :wedding, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :webgalleries, dependent: :destroy
  has_many :portraits, dependent: :destroy
  
  # User roles
  def admin?
    role == 'admin'
  end
  
  def client?
    role == 'client'
  end
  
end

app/models/webgallery.rb
class Webgallery < ActiveRecord::Base
  belongs_to :user
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
  belongs_to :user 
  has_many :invoices, as: :invoiceable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    @user = User.new
    @webgallery = Webgallery.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    # create user
    @user = User.new(params.require(:user).permit(:client_name, :email, :name_primary))
    @user.role = 'client'
    # randomly generated initial password to satisfy validation
    # new password generated when invitation is sent to user
    password = SecureRandom.hex(4)
    @user.password = password
    @user.password_confirmation = password
    if @user.save
      # User created successfully
    else
      flash[:error] = "There was an error creating the user."
    end
    
    redirect_to request.referrer
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params.require(:user).permit(
      :user_name,
      :client_name,
      :name_primary,
      :name_secondary,
      :email,
      :street_address, 
      :city,
      :state,
      :zip_code,
      :country,
      :phone_home,
      :phone_cell
      ))
    redirect_to request.referrer
  end
  
  def destroy
    @user = User.find(params[:id])
    unless @user.admin?
      @user.destroy
    else
      flash[:error] = "Cannot delete admin account."
    end
    redirect_to request.referrer
  end
  
  private
  
  def generate_token
    return "Generate Token Successful!"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def helper_my_business_name
    return 'B-Team Photography'
  end
  
  def helper_title_slogan
    return 'B-Team Photography - Professional Wedding and Portrait Photographers'
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tax_rate_helper.rb
module TaxRateHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_userinfo.html.erb
    
    <%= form_for user do |f| %>

      <p class="medium-text">Personal Details</p>

      <span>Primary contact (or Bride):</span>
      <%= f.text_field :name_primary %>

      <span>Secondary contact (or Groom):</span>
      <%= f.text_field :name_secondary %>

      <span>Street address:</span>
      <%= f.text_field :street_address %>

      <span>City/Town:</span>
      <%= f.text_field :city %>

      <span>State:</span>
      <%= f.text_field :state %>

      <span>Zip code:</span>    
      <%= f.text_field :zip_code %>

      <span>Country:</span>    
      <%= f.text_field :country %>

      <span>Home Phone:</span>    
      <%= f.text_field :phone_home %>

      <span>Cell Phone:</span>    
      <%= f.text_field :phone_cell %>

      <%= f.submit 'Update', class: 'button small radius secondary' %>

    <% end %>
  

app/views/users/index.html.erb
<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">

    <p class="large-text">Add Client</p>

    <%= form_for @user do |f| %>

      <span>Client Name:</span>
      <%= f.text_field :client_name %>
        
      <span>Email:</span>
      <%= f.email_field :email %>

      <span>Primary contact (or Bride):</span>
      <%= f.text_field :name_primary %>

    <%= f.submit 'Add Client', class: 'button small radius secondary' %>

    <% end %>

    <br/>
    <p class="large-text">Client Index</p>

    <% @users.each do |user| %>
    
      <% unless user.admin? %> <!-- Do not display admin account -->
        <table class="table-width-100">
          <thead>
            <tr>
              <th class="table-header-width-100 clearfix">    
                <%= link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure you want to delete client '#{user.client_name}'?" }, class: 'button tiny radius secondary right clear-margin clear-padding' %>
                <span><%= user.client_name %></span><br/>
                <span><%= user.email %></span>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <% unless user.invitations.last.nil? %>
                  <span class="subdued-text">Token: <%= user.invitations.last.token %></span>
                <% else %>
                  <%= link_to 'Send Invitation', send_invitation_path(user), data: { confirm: 'Are you sure you are ready to send the invitation?'} %>
                <% end %>
                <br/>
                <%= link_to "Edit Client Details", user %>    
              </td>
            </tr>

            <tr>
              <td>
                <% if user.wedding.nil? %>
                  <%= link_to 'Add Wedding', add_wedding_path(user) %>
                <% else %>
                  <span><strong>Wedding Photography Event:</strong></span><br/>
                  <span><%= link_to 'View/Edit Wedding Details', user.wedding %></span><br/>

                  <!-- Wedding Invoices -->
                  <% unless user.wedding.invoices.nil? %>
                    <br/><span><strong>Wedding Invoices:</strong></span><br/>
                    <% user.wedding.invoices.each do |invoice| %>
                      <%= link_to "#{invoice.description}", invoice %>

                      <!-- Determine if paid or balance due -->
                      <span class="label round info nudge-up-2"><%= invoice.balance > 0 ? "#{humanized_money_with_symbol(invoice.balance)}" : "Paid" %></span><br/>
                    <% end %>
                  <% end %>
                <% end %>   
              </td>
            </tr>

            <tr>
              <td>
                <!-- Portrait Sessions -->
                <%= link_to 'Add Portrait Session', new_portrait_path(user), class: 'button tiny radius secondary right' %>
                <span><strong>Portrait Sessions:</strong></span><br/>
                <% unless user.portraits.nil? %>
                  <% user.portraits.each do |portrait| %>

                    <%= link_to portrait.title, portrait %>
                    <%= link_to "X", portrait, method: :delete, class: 'label round nudge-up-2 secondary', data: { confirm: "Are you sure you want to delete this portrait session?" } %>
                    <br/>

                  <% end %>
                  <br/>
                  
                  <!-- Portrait Invoices -->
                  <br/><span><strong>Portrait Invoices:</strong></span><br/>
                  <% user.portraits.each do |portrait| %>
                    <% portrait.invoices.each do |invoice| %>
                      <%= link_to invoice.description, invoice %>
                      <span class="label round info nudge-up-2"><%= invoice.balance > 0 ? "#{humanized_money_with_symbol(invoice.balance)}" : "Paid" %></span><br/>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>

            <tr>
              <td>
                <!-- Web Galleries -->
                <span><strong>Web Galleries:</strong></span><br/>
                <% unless user.webgalleries.nil? %>
                  <% user.webgalleries.each do |webgallery| %>
                    <%= link_to webgallery.description, webgallery.url, target: "_blank" %>
                    <%= link_to "X", webgallery, method: :delete, class: 'label round nudge-up-2 secondary', data: { confirm: "Are you sure you want to delete this web gallery?" } %>
                    <br/>
                  <% end %>
                <% end %>

                <!-- Add new web gallery -->
                <%= form_for @webgallery do |f| %>
                  <br/><span>Description:</span>
                  <%= f.text_field :description %>
                  <span>URL:</span>
                  <%= f.text_field :url %>
                  <%= f.hidden_field :user, value: user.id %>
                  <%= f.hidden_field :genre, value: 'wedding' %>
                  <%= f.submit "Add Web Gallery", class: 'button tiny radius secondary right' %>
                <% end %>
              </td>
            </tr>

          </tbody>
        </table>
      <% end %>
    
    <% end %>
    
  </div>
</div>

app/views/users/setup_password.html.erb
<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">
    
    <p class="large-text">Account Setup Confirmation</p>
    
    <p>Please enter and confirm a password with a minimum of 8 characters to finish your account setup. Afterwards, you will be directed to the login page.<p>
    
    <%= form_for @user do |f| %>
    
        <%= f.text_field :client_name %>
    
        <span>Enter password:</span>
        <%= f.password_field :password, autocomplete: "off" %>

        <span>Confirm password:</span>
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
    
    <%= f.submit 'Confirm', class: 'button small radius secondary' %>
    
    <% end %>
    
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">
    
    <%= render partial: 'userinfo', locals: { user: @user } %>
    
    <% if current_user.admin? %>
      <%= link_to 'Back to Client Index', users_path %>
    <% else %>
      <%= link_to 'Back', client_landing_path(current_user) %>
    <% end %>
    
    <br/><br/>
    
  </div>
</div>