config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'client_landing' => 'welcome#client_landing'
  
  devise_for :users, :path_prefix => 'my', :controllers => { :registrations => :registrations }
  resources :users, only: [:index, :show, :update, :create, :destroy]
  delete 'delete_client' => 'users#destroy', as: :delete_client
  get 'change_password_cleanser' => 'users#change_password_cleanser', as: :change_password_cleanser
  
  resources :weddings, only: [:show, :update, :create]
  get 'add_wedding/:id' => 'weddings#create', as: :add_wedding
  
  get 'temporary_password_cleanser/:id' => 'invitations#destroy', as: :temporary_password_cleanser
  get 'confirmation' => 'invitations#confirmation'
  get 'send_invitation/:id' => 'invitations#create', as: :send_invitation
  
  resources :invoices
  resources :items
  post 'create_charge/:id' => 'charges#create', as: :create_charge
  get 'new_charge/:id' => 'charges#new', as: :new_charge
  get 'new_payment/:id' => 'charges#payment', as: :new_payment

  resources :collections, only: [:index, :create, :edit, :update, :destroy]
  resources :images, only: [:create, :destroy]

  get 'gallery_images/:genre' => 'images#gallery_images'
  get 'add_image/:genre' => "images#add_image"

  resources :reviews, only: [:create, :update, :destroy]
  get 'get_reviews/:genre' => 'reviews#reviews'

  resources :webgalleries, only: [:create, :destroy]
  
  resources :portraits, except: [:new]
  get 'new_portrait/:id' => 'portraits#new', as: :new_portrait
  
  
  
  
  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :collection

	def url
		return "http://bteamphoto.com/images/#{genre}/#{name}"
	end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  before_create :generate_token
  
  private
  
  def generate_token
    self.token = "#{ SecureRandom.urlsafe_base64 }"
  end
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :invoiceable, polymorphic: true
  monetize :balance_cents
  monetize :payment_cents
  has_many :items

  before_create :set_default_tax_rate_if_nil

  def set_default_tax_rate_if_nil
  	self.tax_rate ||= ".08"
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice
  monetize :price_cents
end

app/models/portrait.rb
class Portrait < ActiveRecord::Base
  belongs_to :user
  has_many :invoices, as: :invoiceable
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  has_one :wedding, dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :webgalleries, dependent: :destroy
  has_many :portraits, dependent: :destroy
  
  # User roles
  def admin?
    role == 'admin'
  end
  
  def client?
    role == 'client'
  end
  
end

app/models/webgallery.rb
class Webgallery < ActiveRecord::Base
  belongs_to :user
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
  belongs_to :user 
  has_many :invoices, as: :invoiceable
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    @invoice = Invoice.find(params[:id])

    # create customer with unique token
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    
    # create charge (Amount is its own class/model ... or ... pass this value in as argument/params?)
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @invoice.payment_cents,
      description: "B-Team Photography payment from: #{current_user.email}",
      currency: 'usd'
    )
  
  flash[:notice] = "Payment successfully processed!"
  @invoice.update_attributes(balance_cents: 0, payment_cents: 0)
  redirect_to @invoice
  
  # catch any errors and go back to payment process page
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @invoice = Invoice.find(params[:id])
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      name: "B-Team Photography",
      description: @invoice.description,
      email: current_user.email,
      amount: @invoice.payment_cents
    }
  end

  def payment
    @invoice = Invoice.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def helper_my_business_name
    return 'B-Team Photography'
  end
  
  def helper_title_slogan
    return 'B-Team Photography - Professional Wedding and Portrait Photographers'
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tax_rate_helper.rb
module TaxRateHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/new.html.erb
<script src="https://checkout.stripe.com/checkout.js"></script>

<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">

	<p class="large-text">Payment</p>
	<p class="medium-text">
		<span><%= @invoice.description %></span><br/>
		<span class="subdued-text">Current payment amount: <span class="subdued-text" id="invoice_balance"><%= humanized_money_with_symbol(@invoice.payment) %></span></span>
	</p>

	<p>Ensure the payment amount above is correct, then click the button below. For other payment arrangements, please contact us at <a href="mailto:bteamphoto@gmail.com">bteamphoto@gmail.com</a>.</p>

	<%= form_tag create_charge_path(@invoice) do %>
   <script 
	class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
	data-label="Confirm and Pay with Card"
   	data-allow-remember-me="false"
    data-key="<%= @stripe_btn_data[:key] %>"
    data-name="<%= @stripe_btn_data[:name] %>"
    data-description="<%= @stripe_btn_data[:description] %>"
    data-email="<%= @stripe_btn_data[:email] %>"
    data-amount=<%= @stripe_btn_data[:amount] %> >
 	</script>
 <% end %>

 </div>
</div>

app/views/charges/payment.html.erb
<div class="row">
  <div class="small-10 small-centered large-6 large-uncentered columns">

	<p class="large-text">Payment Selection</p>
	
	<p>Pay Remaining Balance: <%= humanized_money_with_symbol(@invoice.balance) %></p>
	<p>Pay Another Amount: <%= humanized_money_with_symbol(@invoice.payment) %></p>

 </div>
</div>